name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
        unzip android-ndk-r21-linux-x86_64.zip
    - name: Build
      run: ANDROID_NDK_HOME=./android-ndk-r21 ./build.sh
