name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
        unzip android-ndk-r21-linux-x86_64.zip
    - name: Build (AArch64)
      run: ANDROID_NDK_HOME=./android-ndk-r21 CXX=aarch64-linux-android29-clang++ ./build.sh
    - name: Build (ARMv7-A)
      run: ANDROID_NDK_HOME=./android-ndk-r21 CXX=armv7a-linux-androideabi29-clang++ ./build.sh
    - name: Build (i686)
      run: ANDROID_NDK_HOME=./android-ndk-r21 CXX=i686-linux-android29-clang++ ./build.sh
    - name: Build (x86_64)
      run: ANDROID_NDK_HOME=./android-ndk-r21 CXX=x86_64-linux-android29-clang++ ./build.sh
